[project]
name = "ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "shivam chaudhary", email = "shivamchy076@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
ai = "ai:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
